### ISSUE TITLE
按照说明安装完了, 结果没有显示侧边栏

### ISSUE THREAD

**Issue by chong-w** [zthxxx/hexo-theme-Wikitten#13]
截图如下：
![image](https://user-images.githubusercontent.com/30772228/29971815-5d290be4-8f5c-11e7-83b3-dc3a662a81d5.png)
我把所有的插件都装了 而且站点配置和主题配置也全按照推荐改了
不知道是哪的问题

**Comment by chong-w** [comment]
问题解决，原来是文章没有设置分类

**Comment by zthxxx** [comment]
请检查下主题配置文件 `_config.yml` 中的 `customize.sidebar` 是否为 `left` 或 `right`，`widgets` 下是否开启了 `- category`，侧边栏的显示是由这两者控制的，设置错误都不会显示

```yaml
# Customize
customize:
  sidebar: left # sidebar position, options: left, right

# Widgets
widgets: # default use category only
    - category
```
