### ISSUE TITLE
搜索功能无法生效

### ISSUE THREAD

**Issue by 941968215** [zthxxx/hexo-theme-Wikitten#14]
主题配置: 
```
# Menus
menu:
  首页: /
  归档: /archives
  分类: /categories
  标签: /tags
  关于: /about

# Customize
customize:
    logo:
        enabled: true
        width: 40
        height: 40
        url: /logo.png
    profile:
        enabled: false # Whether to show profile bar
        avatar: css/images/czxyl.png
        gravatar: czxyl@protonmail.com # Gravatar email address, if you enable Gravatar, your avatar config will be overriden
        author: czxyl
        author_title: 辣稽
        location: Suzhou, China
        follow: 
    highlight: monokai
    sidebar: left # sidebar position, options: left, right
    category_perExpand: false # enable article categories list per expanding
    thumbnail: true # enable posts thumbnail, options: true, false
    favicon: C:\Users\HP\Documents\czxyl\source # path to favicon
    default_index_file: index.md # if this, it will display at site index instead of default index page
    social_links:
        stack-overflow: https://stackoverflow.com/users/6949852/czxyl
        #segmentfault: https://segmentfault.com/u/czxyl 
        #codereview-stackexchange: https://codereview.stackexchange.com/users/148249/czxyl
    social_link_tooltip: true # enable the social link tooltip, options: true, false

# Widgets
widgets: # default use category only
    - category
    #- recent_posts
    - archive
    #- tag
    - tagcloud
    #- links
    
# Excerpt 
## Auto creat excerpt with not <!--more-->
## Enable will truncate auto_excerpt.lines rows in post head to replace excerpt.
auto_excerpt:
    enable: true
    lines: 5


# Search
search:
    insight: true # you need to install `hexo-generator-json-content` before using Insight Search
    swiftype: # enter swiftype install key here
    baidu: false # you need to disable other search engines to use Baidu search, options: true, false

# History version 
history_control: # make you wiki has history version control in page
    enable: false
    server_link: https://github.com # recommend use GitHub https://github.com
    user: zthxxx
    repertory: Wiki-site
    branch: writing

# Comment
comment:
    disqus: # enter disqus shortname here
    duoshuo: # enter duoshuo shortname here
    youyan: 2143118 # enter youyan uid here

# Share
share: default # options: jiathis, bdshare, addtoany, default

# Plugins
plugins:
    lightgallery: true # options: true, false
    justifiedgallery: true # options: true, false
    google_analytics: # enter the tracking ID for your Google Analytics
    google_site_verification: # enter Google site verification code
    baidu_analytics: # enter Baidu Analytics hash key

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
    links:

```

站点配置: 
```
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/
# Menus
menu:
  Home: .
  Archives: archives
  Categories: categories
  Tags: tags
  About: about
# Site
title: czxylのBlog
subtitle: czxyl
description: I'll never be big enough to pay your dues
author: czxyl
language: zh-CN
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://czxyl.me
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

algolia:
  applicationID: VAUYH87DND
  apiKey: 086e59cf39a82c6c95008f0eb2e19c83
  adminApiKey: e63a84233f7fe6775766f7f362f36444
  indexName: czxyl
  chunkSize: 5000

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

search:
  path: search.xml
  field: post
  format: html
  limit: 10000

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions



### 代码高亮
#highlight:
#  enable: true
#  line_number: true
#  tab_replace:

#yilia
jsonContent:
  meta: false
  pages: false
  posts:
    title: true
    date: true
    path: true
    text: false
    raw: false
    content: false
    slug: false
    updated: false
    comments: false
    link: false
    permalink: false
    excerpt: false
    categories: false
    tags: true


#Feed Atom
feed:
type: atom
path: atom.xml
limit: 20

markdown_it_plus:
    highlight: true
    html: true
    xhtmlOut: true
    breaks: true
    langPrefix:
    linkify: true
    typographer:
    quotes: “”‘’
    pre_class: highlight

sitemap:
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml
## Themes: https://hexo.io/themes/
theme: Wikitten

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:941968215/941968215.github.io.git
  branch: master

cnzz: 1261133190
```

我的网址: czxyl.me 

无法搜索内容. 

已经按照了 "hexo-generator-json-content" 插件

**Comment by zthxxx** [comment]
我看了你站点的 `content.json` 文件，初步判断是插件配置的问题，你可以尝试下主题[推荐的站点插件配置](https://github.com/zthxxx/hexo-theme-Wikitten#configuration) 中的 `JsonContent` 项

```yaml
### JsonContent
jsonContent:
  meta: false
  pages:
    title: true
    date: true
    path: true
    text: true
  posts:
    title: true
    date: true
    path: true
    text: true
    tags: true
    categories: true
  ignore:
    - 404.html
```
