### ISSUE TITLE
[报错] 使用了 jsonContent 插件导致生成页面报错

### ISSUE THREAD

**Issue by rosuH** [zthxxx/hexo-theme-Wikitten#5]
OS:  Ubuntu Server 16.04.2 LTS x64, 4.4.0-66-generic
```
"hexo": {
    "version": "3.2.2"
  },
  "dependencies": {
    "hexo": "^3.2.0",
    "hexo-autonofollow": "^1.0.1",
    "hexo-directory-category": "^1.0.3",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-feed": "^1.2.0",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-json-content": "^3.0.1",
    "hexo-generator-sitemap": "^1.1.2",
    "hexo-generator-tag": "^0.2.0",
    "hexo-inject": "^1.0.0",
    "hexo-math": "^3.0.2",
    "hexo-renderer-ejs": "^0.2.0",
    "hexo-renderer-marked": "^0.2.10",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-server": "^0.2.0"
  }
```

安装教程中，在**站点**的配置文件加入如下配置后，使用`hexo g`生成时报错。
```
jsonContent:
  meta: false
  pages:
    title: true
    date: true
    path: true
    text: true
    tags: true
    categories: true
  posts:
    title: true
    date: true
    path: true
    text: true
    tags: true
    categories: true
  ignore:
    - 404.html
```
报错信息如下：
```
TypeError: Cannot read property 'map' of undefined
    at setContent (/home/rosu/wiki/node_modules/hexo-generator-json-content/index.js:85:24)
    at pagesNames.reduce (/home/rosu/wiki/node_modules/hexo-generator-json-content/index.js:112:52)
    at Array.reduce (native)
    at site.pages.filter.map.page (/home/rosu/wiki/node_modules/hexo-generator-json-content/index.js:112:30)
    at Query.map (/home/rosu/wiki/node_modules/warehouse/lib/query.js:229:17)
    at Hexo.hexo.extend.generator.register.site (/home/rosu/wiki/node_modules/hexo-generator-json-content/index.js:112:7)
    at Hexo.tryCatcher (/home/rosu/wiki/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/home/rosu/wiki/node_modules/bluebird/js/release/method.js:15:34)
    at /home/rosu/wiki/node_modules/hexo/lib/hexo/index.js:337:24
    at tryCatcher (/home/rosu/wiki/node_modules/bluebird/js/release/util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (/home/rosu/wiki/node_modules/bluebird/js/release/map.js:61:38)
    at MappingPromiseArray.PromiseArray._iterate (/home/rosu/wiki/node_modules/bluebird/js/release/promise_array.js:114:31)
    at MappingPromiseArray.init (/home/rosu/wiki/node_modules/bluebird/js/release/promise_array.js:78:10)
    at MappingPromiseArray._asyncInit (/home/rosu/wiki/node_modules/bluebird/js/release/map.js:30:10)
    at Async._drainQueue (/home/rosu/wiki/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/home/rosu/wiki/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/rosu/wiki/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
FATAL Cannot read property 'map' of undefined
TypeError: Cannot read property 'map' of undefined
    at setContent (/home/rosu/wiki/node_modules/hexo-generator-json-content/index.js:85:24)
    at pagesNames.reduce (/home/rosu/wiki/node_modules/hexo-generator-json-content/index.js:112:52)
    at Array.reduce (native)
    at site.pages.filter.map.page (/home/rosu/wiki/node_modules/hexo-generator-json-content/index.js:112:30)
    at Query.map (/home/rosu/wiki/node_modules/warehouse/lib/query.js:229:17)
    at Hexo.hexo.extend.generator.register.site (/home/rosu/wiki/node_modules/hexo-generator-json-content/index.js:112:7)
    at Hexo.tryCatcher (/home/rosu/wiki/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/home/rosu/wiki/node_modules/bluebird/js/release/method.js:15:34)
    at /home/rosu/wiki/node_modules/hexo/lib/hexo/index.js:337:24
    at tryCatcher (/home/rosu/wiki/node_modules/bluebird/js/release/util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (/home/rosu/wiki/node_modules/bluebird/js/release/map.js:61:38)
    at MappingPromiseArray.PromiseArray._iterate (/home/rosu/wiki/node_modules/bluebird/js/release/promise_array.js:114:31)
    at MappingPromiseArray.init (/home/rosu/wiki/node_modules/bluebird/js/release/promise_array.js:78:10)
    at MappingPromiseArray._asyncInit (/home/rosu/wiki/node_modules/bluebird/js/release/map.js:30:10)
    at Async._drainQueue (/home/rosu/wiki/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/home/rosu/wiki/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/rosu/wiki/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)

```

-----
不知道是该插件问题还是？

**Comment by rosuH** [comment]
注释掉`tags`和`categories`就可以正常生成了。
```
jsonContent:
  meta: true
  pages:
    title: true
    date: true
    path: true
    text: true
#    tags: true
#    categories: true
  posts:
    title: true
    date: true
    path: true
    text: true
    tags: true
    categories: true
  ignore:
    - 404.html
```
