### ISSUE TITLE
请问如何禁用文章中的目录功能？

### ISSUE THREAD

**Issue by rosuH** [zthxxx/hexo-theme-Wikitten#6]
查询了 `Hexo` 和 `Wikitten` 官方的文档，没有找到这样的配置参数。

目录功能应该是通过插件实现的？但是我对`Hexo`的插件不是很熟悉，希望您告知一下。谢谢。

下图右边的目录。
![snipaste_20170405_162415.png](https://ooo.0o0.ooo/2017/04/05/58e4ab375e006.png)

**Comment by zthxxx** [comment]
@rosuH 
Just add **`toc: false`** to the **front-matter** of your post, like:
```yaml
---
title: xxx
date: 2017-04-06 09:57:57
toc: false
---
```
