### ISSUE TITLE
你好，请问有没有什么办法可以修改code block的背景色呢？那个大黑框看着有点不舒服

### ISSUE THREAD

**Issue by hinzer** [zthxxx/hexo-theme-Wikitten#62]

**Comment by zthxxx** [comment]
可以的，加一下自定义的 css 覆盖就好，但是建议不要

```css
.article-entry .highlight {
  background: #555;
}
```
