### ISSUE TITLE
生成站点报错：SyntaxError: Block-scoped declarations

### ISSUE THREAD

**Issue by rosuH** [zthxxx/hexo-theme-Wikitten#8]
新建的一个站点，使用默认主题不会出错。

站点的配置文件采用推荐的参数：
```
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: rosu's Wiki
subtitle:
description:
author: rosuh
language: zh-cn
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yoursite.com
root: /
permalink: wiki/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - README.md
  - '_posts/**/embed_page/**'

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

## https://github.com/hexojs/hexo-renderer-marked
marked:
  gfm: true


# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
### JsonContent
jsonContent:
  meta: false
  pages:
    title: true
    date: true
    path: true
    text: true
  posts:
    title: true
    date: true
    path: true
    text: true
    tags: true
    categories: true
  ignore:
    - 404.html
    
### Creat sitemap
sitemap:
  path: sitemap.xml
## Themes: https://hexo.io/themes/
theme: Wikitten

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type:
```

主题设置采用默认的设置，也就是还没自行设置。
然后执行`hexo g`命令产生错误：
```
rosu@rosu-ubuntu:~/wiki$ hexo g
INFO  Start processing
ERROR Process failed: layout/common/article.ejs
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode in "/home/rosu/wiki/themes/Wikitten/layout/common/article.ejs"
    at Function (native)
    at Object.exports.compile (/home/rosu/wiki/node_modules/ejs/lib/ejs.js:242:14)
    at Function.ejsRenderer.compile (/home/rosu/wiki/node_modules/hexo-renderer-ejs/lib/renderer.js:11:14)
    at View._precompile (/home/rosu/wiki/node_modules/hexo/lib/theme/view.js:119:29)
    at View (/home/rosu/wiki/node_modules/hexo/lib/theme/view.js:13:8)
    at new Theme._View.View (/home/rosu/wiki/node_modules/hexo/lib/theme/index.js:37:10)
    at Theme.setView (/home/rosu/wiki/node_modules/hexo/lib/theme/index.js:71:20)
    at /home/rosu/wiki/node_modules/hexo/lib/theme/processors/view.js:14:14
    at tryCatcher (/home/rosu/wiki/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/rosu/wiki/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/rosu/wiki/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/rosu/wiki/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/rosu/wiki/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/home/rosu/wiki/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/home/rosu/wiki/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/home/rosu/wiki/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/home/rosu/wiki/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/rosu/wiki/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/rosu/wiki/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/home/rosu/wiki/node_modules/bluebird/js/release/promise.js:638:18)
    at /home/rosu/wiki/node_modules/bluebird/js/release/nodeback.js:42:21
    at /home/rosu/wiki/node_modules/graceful-fs/graceful-fs.js:78:16
INFO  Files loaded in 554 ms
WARN  Partial common/article does not exist. (in page.ejs)
WARN  Partial common/article does not exist. (in post.ejs)
WARN  Partial common/article does not exist. (in index.ejs)
INFO  0 files generated in 331 ms
```

现在不知道是什么原因...麻烦抽时间看一下。

------
谢谢
